export const LOGIN_USER = "LOGIN_USER";
export const START_LOADING_DATA = "START_LOADING_DATA";
export const END_LOADING_DATA = "END_LOADING_DATA";
export const GET_ERROR_STATUS_CODE = "GET_ERROR_STATUS_CODE";
export const CHECK_TOKEN_VALIDITY = "CHECK_TOKEN_VALIDITY";
